// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTdmNRN3KLltSCPKeCq1cUvy_f1QRol0U',
    appId: '1:439123124050:web:b0872e2d90f7ad7f0a248b',
    messagingSenderId: '439123124050',
    projectId: 'endless-trivia-86bd4',
    authDomain: 'endless-trivia-86bd4.firebaseapp.com',
    storageBucket: 'endless-trivia-86bd4.firebasestorage.app',
    measurementId: 'G-QKRLJ39FLD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArG9swebtw1h9v5ELqBoQnRk8sRlksfus',
    appId: '1:439123124050:android:7e545af48931b1180a248b',
    messagingSenderId: '439123124050',
    projectId: 'endless-trivia-86bd4',
    storageBucket: 'endless-trivia-86bd4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJurueSnPZrEfCcN8sATnoEr-5z6s6yUY',
    appId: '1:439123124050:ios:f94781ab1d7aa26b0a248b',
    messagingSenderId: '439123124050',
    projectId: 'endless-trivia-86bd4',
    storageBucket: 'endless-trivia-86bd4.firebasestorage.app',
    iosBundleId: 'com.example.endlessTrivia',
  );
}
